Try support OCaml 5.2
Compilation fails with:
```
File "lib/uTop.ml", line 284, characters 18-26:
Error: Unbound value Exp.fun_
```

Because `fun_` was removed by commit 739f574cd1bbda3489809e25949c4cd1c262d407

It is unclear what to do with block from lines 280-294

Additionally, in file `lib/worker.cppo.ml`, lines 218-220, this was added:
```
                 visibility = Visible
```
Although it compiles, it is unclear if it is the right thing to do